@startuml Containers
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(engineer, "Инженер")
Container_Boundary(platform, "IoT Platform") {
    Container(queue, "Kafka", "Message Broker", "Очередь сообщений для событий")
    Container(ext_auth, "Keycloak", "Identity Server", "SSO/OAuth2 сервер")
    Container(ext_bpm, "Camunda", "BPM Engine", "Движок workflow процессов")
}

Rel(device, queue, "Отправка данных (producer)", "Kafka protocol")
Rel(engineer, ext_auth, "Вход в систему", "Keycloak (OIDC)")
Rel(engineer, ext_bpm, "Мониторинг процессов", "HTTP (Camunda Cockpit)")

@enduml